hydra:
  output_subdir: null  
  run:
    dir: .

model:
  medical: config/model/rf_model
  # - hdb: model/...

data:
  raw: 
    hdb: data/raw/01_hdb_resale_transactions.csv
    medical: data/raw/02_medical_records.csv

prediction:
  medical_column: ['age', 'chest_pain', 'resting_BP', 'cholesterol', 'max_HR', 'old_peak', 'ST_slope']
  # processed: data/processed/processed.csv
  # final: data/final/final.csv