hydra:
  output_subdir: null  
  run:
    dir: .

model:
  medical: config/model/rf_model
  # - hdb: model/...

data:
  raw: 
    hdb: data/raw/01_hdb_resale_transactions.csv
    medical: data/raw/02_medical_records.csv

  # processed: data/processed/processed.csv
  # final: data/final/final.csv